// 各ページの H2 見出しをキーワードとして保持する検索インデックス
export const searchIndex: Record<string, string[]> = {
  '/': [
    'なぜ Three.js を学ぶのか',
    '学習フロー',
    'このガイドの特徴',
    'キーボードショートカット',
    '準備はいいですか？',
  ],
  '/basics/scene': [
    'Three.js の 3 つの要素',
    '最初のシーンを作る',
    'コードの流れ',
  ],
  '/basics/camera': [
    'PerspectiveCamera とは',
    'カメラのコード',
    'カメラの位置と向き',
  ],
  '/basics/renderer': [
    'WebGLRenderer とは',
    'レンダラーの基本設定',
    '各設定の解説',
    'アンチエイリアスの効果',
    'ウィンドウリサイズ対応',
  ],
  '/basics/geometry': [
    'ジオメトリとは',
    'BoxGeometry を試してみよう',
    'よく使うジオメトリ一覧',
  ],
  '/basics/material': [
    '3 つの基本マテリアル',
    'マテリアルの選び方',
  ],
  '/basics/light': [
    '3 つの基本ライト',
    'ライトを調整してみよう',
    'ライトのコード',
    'その他のライト',
  ],
  '/basics/animation': [
    'アニメーションの仕組み',
    '基本のアニメーションループ',
    'コードの流れ',
    '回転する立方体',
    '回転以外のアニメーション',
  ],
  '/applied/textures': [
    'TextureLoader の基本',
    'UV マッピングとは',
    'チェッカーボードテクスチャ',
  ],
  '/applied/model-loading': [
    'glTF フォーマットとは',
    'GLTFLoader の使い方',
    'React Three Fiber での読み込み',
    'プリミティブによる構造物の例',
    'モデル最適化のポイント',
  ],
  '/applied/interaction': [
    'Raycaster の仕組み',
    'Raycaster のコード',
    'インタラクティブなボックス',
    'R3F でのインタラクション',
  ],
  '/applied/responsive': [
    'リサイズ対応が必要な理由',
    'リサイズイベントの実装',
    'コンテナ要素に合わせる場合',
    'レスポンシブなシーンの例',
    'R3F でのレスポンシブ対応',
  ],
  '/applied/orbit-controls': [
    'OrbitControls の機能',
    'パラメータを調整してみよう',
    'OrbitControls のセットアップ',
  ],
  '/applied/post-processing': [
    'EffectComposer の仕組み',
    'Three.js での EffectComposer',
    'Bloom エフェクト',
    'R3F でのポストプロセシング',
    'よく使うポストプロセシングエフェクト',
  ],
  '/practical/r3f-basics': [
    'R3F の基本概念',
    'バニラ Three.js vs R3F の比較',
    'useFrame でアニメーション',
    'R3F コンポーネントの書き方',
  ],
  '/practical/r3f-drei': [
    '1. OrbitControls',
    '2. Environment',
    '3. Text',
    '4. Float',
    '5. MeshWobbleMaterial',
    'Float + MeshWobbleMaterial デモ',
  ],
  '/practical/portfolio-scene': [
    '完成シーンのプレビュー',
    'シーンの構成要素',
    '完全なソースコード',
    '使用している技術の整理',
  ],
  '/game-dev/overview': [
    'ゲームアーキテクチャの全体像',
    'ゲームループの基本構造',
    '飛行機プレビュー',
    'R3F でのゲームループ',
  ],
  '/game-dev/aircraft': [
    '飛行機の構造',
    '飛行機モデルのプレビュー',
    'キーボード操作の実装',
    'キーマッピング',
  ],
  '/game-dev/terrain': [
    'プロシージャル地形の仕組み',
    '地形プレビュー',
    '地形生成アルゴリズム',
    '空と雲の実装',
  ],
  '/game-dev/physics': [
    '飛行の 4 つの力',
    '物理シミュレーション プレビュー',
    '物理更新関数の実装',
    'useFrame での統合',
  ],
  '/game-dev/camera': [
    '3 つのカメラモード',
    '三人称カメラのプレビュー',
    'カメラ追従ロジック（lerp）',
    '視点切替の実装',
  ],
  '/game-dev/hud-gameloop': [
    'HUD（Head-Up Display）',
    'ミニゲーム プレビュー',
    'ゲーム状態の管理',
    'チェックポイント当たり判定',
    'HUD の実装パターン',
  ],
};
